server:
  port: 8082

spring:
  application:
    name: xiaoming #  设置服务名

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #  设置注册中心地址
  instance:
      prefer-ip-address: true  #将自己的ip注册到EuekaServer上